//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Organisation = newOrganisationTable("public", "Organisation", "")

type organisationTable struct {
	postgres.Table

	// Columns
	UniqueId   postgres.ColumnString
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp
	Name       postgres.ColumnString
	WebsiteUrl postgres.ColumnString
	LogoUrl    postgres.ColumnString
	FaviconUrl postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type OrganisationTable struct {
	organisationTable

	EXCLUDED organisationTable
}

// AS creates new OrganisationTable with assigned alias
func (a OrganisationTable) AS(alias string) *OrganisationTable {
	return newOrganisationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrganisationTable with assigned schema name
func (a OrganisationTable) FromSchema(schemaName string) *OrganisationTable {
	return newOrganisationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrganisationTable with assigned table prefix
func (a OrganisationTable) WithPrefix(prefix string) *OrganisationTable {
	return newOrganisationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrganisationTable with assigned table suffix
func (a OrganisationTable) WithSuffix(suffix string) *OrganisationTable {
	return newOrganisationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrganisationTable(schemaName, tableName, alias string) *OrganisationTable {
	return &OrganisationTable{
		organisationTable: newOrganisationTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newOrganisationTableImpl("", "excluded", ""),
	}
}

func newOrganisationTableImpl(schemaName, tableName, alias string) organisationTable {
	var (
		UniqueIdColumn   = postgres.StringColumn("UniqueId")
		CreatedAtColumn  = postgres.TimestampColumn("CreatedAt")
		UpdatedAtColumn  = postgres.TimestampColumn("UpdatedAt")
		NameColumn       = postgres.StringColumn("Name")
		WebsiteUrlColumn = postgres.StringColumn("WebsiteUrl")
		LogoUrlColumn    = postgres.StringColumn("LogoUrl")
		FaviconUrlColumn = postgres.StringColumn("FaviconUrl")
		allColumns       = postgres.ColumnList{UniqueIdColumn, CreatedAtColumn, UpdatedAtColumn, NameColumn, WebsiteUrlColumn, LogoUrlColumn, FaviconUrlColumn}
		mutableColumns   = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, NameColumn, WebsiteUrlColumn, LogoUrlColumn, FaviconUrlColumn}
	)

	return organisationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UniqueId:   UniqueIdColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		Name:       NameColumn,
		WebsiteUrl: WebsiteUrlColumn,
		LogoUrl:    LogoUrlColumn,
		FaviconUrl: FaviconUrlColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
