//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Subscribers = newSubscribersTable("public", "subscribers", "")

type subscribersTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz
	DeletedAt postgres.ColumnTimestampz
	UniqueID  postgres.ColumnInteger
	ListID    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SubscribersTable struct {
	subscribersTable

	EXCLUDED subscribersTable
}

// AS creates new SubscribersTable with assigned alias
func (a SubscribersTable) AS(alias string) *SubscribersTable {
	return newSubscribersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubscribersTable with assigned schema name
func (a SubscribersTable) FromSchema(schemaName string) *SubscribersTable {
	return newSubscribersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubscribersTable with assigned table prefix
func (a SubscribersTable) WithPrefix(prefix string) *SubscribersTable {
	return newSubscribersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubscribersTable with assigned table suffix
func (a SubscribersTable) WithSuffix(suffix string) *SubscribersTable {
	return newSubscribersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubscribersTable(schemaName, tableName, alias string) *SubscribersTable {
	return &SubscribersTable{
		subscribersTable: newSubscribersTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newSubscribersTableImpl("", "excluded", ""),
	}
}

func newSubscribersTableImpl(schemaName, tableName, alias string) subscribersTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn = postgres.TimestampzColumn("deleted_at")
		UniqueIDColumn  = postgres.IntegerColumn("unique_id")
		ListIDColumn    = postgres.IntegerColumn("list_id")
		allColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, UniqueIDColumn, ListIDColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, UniqueIDColumn, ListIDColumn}
	)

	return subscribersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		UniqueID:  UniqueIDColumn,
		ListID:    ListIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
