//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AccessLogType = &struct {
	WebInterface postgres.StringExpression
	APIAccess    postgres.StringExpression
}{
	WebInterface: postgres.NewEnumValue("web_interface"),
	APIAccess:    postgres.NewEnumValue("api_access"),
}
