//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AiChatVisibilityEnum = &struct {
	Public  postgres.StringExpression
	Private postgres.StringExpression
}{
	Public:  postgres.NewEnumValue("Public"),
	Private: postgres.NewEnumValue("Private"),
}
