//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AiModelEnum = &struct {
	Mistral     postgres.StringExpression
	Gpt4o       postgres.StringExpression
	Gemini15pro postgres.StringExpression
	Gpt4mini    postgres.StringExpression
	Gpt35turbo  postgres.StringExpression
	Claude35    postgres.StringExpression
}{
	Mistral:     postgres.NewEnumValue("Mistral"),
	Gpt4o:       postgres.NewEnumValue("Gpt4o"),
	Gemini15pro: postgres.NewEnumValue("Gemini1.5Pro"),
	Gpt4mini:    postgres.NewEnumValue("GPT4Mini"),
	Gpt35turbo:  postgres.NewEnumValue("Gpt3.5Turbo"),
	Claude35:    postgres.NewEnumValue("Claude3.5"),
}
