//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var CampaignStatus = &struct {
	Draft     postgres.StringExpression
	Running   postgres.StringExpression
	Finished  postgres.StringExpression
	Paused    postgres.StringExpression
	Cancelled postgres.StringExpression
}{
	Draft:     postgres.NewEnumValue("draft"),
	Running:   postgres.NewEnumValue("running"),
	Finished:  postgres.NewEnumValue("finished"),
	Paused:    postgres.NewEnumValue("paused"),
	Cancelled: postgres.NewEnumValue("cancelled"),
}
