//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ConversationStatusEnum = &struct {
	Active   postgres.StringExpression
	Closed   postgres.StringExpression
	Deleted  postgres.StringExpression
	Resolved postgres.StringExpression
}{
	Active:   postgres.NewEnumValue("Active"),
	Closed:   postgres.NewEnumValue("Closed"),
	Deleted:  postgres.NewEnumValue("Deleted"),
	Resolved: postgres.NewEnumValue("Resolved"),
}
