//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MessageTypeEnum = &struct {
	Text        postgres.StringExpression
	Image       postgres.StringExpression
	Video       postgres.StringExpression
	Audio       postgres.StringExpression
	Document    postgres.StringExpression
	Sticker     postgres.StringExpression
	Location    postgres.StringExpression
	Contacts    postgres.StringExpression
	Reaction    postgres.StringExpression
	Address     postgres.StringExpression
	Interactive postgres.StringExpression
	Template    postgres.StringExpression
}{
	Text:        postgres.NewEnumValue("Text"),
	Image:       postgres.NewEnumValue("Image"),
	Video:       postgres.NewEnumValue("Video"),
	Audio:       postgres.NewEnumValue("Audio"),
	Document:    postgres.NewEnumValue("Document"),
	Sticker:     postgres.NewEnumValue("Sticker"),
	Location:    postgres.NewEnumValue("Location"),
	Contacts:    postgres.NewEnumValue("Contacts"),
	Reaction:    postgres.NewEnumValue("Reaction"),
	Address:     postgres.NewEnumValue("Address"),
	Interactive: postgres.NewEnumValue("Interactive"),
	Template:    postgres.NewEnumValue("Template"),
}
