//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrganizaRolePermissionEnum = &struct {
	GetTeam            postgres.StringExpression
	UpdateTeam         postgres.StringExpression
	GetCamaign         postgres.StringExpression
	UpdateCampaign     postgres.StringExpression
	GetConversation    postgres.StringExpression
	UpdateConversation postgres.StringExpression
	GetList            postgres.StringExpression
	UpdateList         postgres.StringExpression
	GetApiKey          postgres.StringExpression
	UpdateApikey       postgres.StringExpression
	GetAppSettings     postgres.StringExpression
	UpdateAppSettings  postgres.StringExpression
}{
	GetTeam:            postgres.NewEnumValue("GetTeam"),
	UpdateTeam:         postgres.NewEnumValue("UpdateTeam"),
	GetCamaign:         postgres.NewEnumValue("GetCamaign"),
	UpdateCampaign:     postgres.NewEnumValue("UpdateCampaign"),
	GetConversation:    postgres.NewEnumValue("GetConversation"),
	UpdateConversation: postgres.NewEnumValue("UpdateConversation"),
	GetList:            postgres.NewEnumValue("GetList"),
	UpdateList:         postgres.NewEnumValue("UpdateList"),
	GetApiKey:          postgres.NewEnumValue("GetApiKey"),
	UpdateApikey:       postgres.NewEnumValue("UpdateApikey"),
	GetAppSettings:     postgres.NewEnumValue("GetAppSettings"),
	UpdateAppSettings:  postgres.NewEnumValue("UpdateAppSettings"),
}
