//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrgRolePermissionEnum = &struct {
	GetColonOrganizationmember     postgres.StringExpression
	CreateColonOrganizationmember  postgres.StringExpression
	UpdateColonOrganizationmember  postgres.StringExpression
	DeleteColonOrganizationmember  postgres.StringExpression
	GetColonCampaign               postgres.StringExpression
	CreateColonCampaign            postgres.StringExpression
	UpdateColonCampaign            postgres.StringExpression
	DeleteColonCampaign            postgres.StringExpression
	GetColonConversation           postgres.StringExpression
	UpdateColonConversation        postgres.StringExpression
	DeleteColonConversation        postgres.StringExpression
	AssignColonConversation        postgres.StringExpression
	UnassignColonConversation      postgres.StringExpression
	GetColonList                   postgres.StringExpression
	CreateColonList                postgres.StringExpression
	UpdateColonList                postgres.StringExpression
	DeleteColonList                postgres.StringExpression
	GetColonTag                    postgres.StringExpression
	CreateColonTag                 postgres.StringExpression
	UpdateColonTag                 postgres.StringExpression
	DeleteColonTag                 postgres.StringExpression
	GetColonApikey                 postgres.StringExpression
	RegenerateColonApikey          postgres.StringExpression
	GetColonAppsettings            postgres.StringExpression
	UpdateColonAppsettings         postgres.StringExpression
	GetColonContact                postgres.StringExpression
	CreateColonContact             postgres.StringExpression
	UpdateColonContact             postgres.StringExpression
	DeleteColonContact             postgres.StringExpression
	BulkimportColonContacts        postgres.StringExpression
	GetColonPrimaryanalytics       postgres.StringExpression
	GetColonSecondaryanalytics     postgres.StringExpression
	GetColonCampaignanalytics      postgres.StringExpression
	UpdateColonOrganization        postgres.StringExpression
	GetColonOrganizationrole       postgres.StringExpression
	CreateColonOrganizationrole    postgres.StringExpression
	UpdateColonOrganizationrole    postgres.StringExpression
	DeleteColonOrganizationrole    postgres.StringExpression
	UpdateColonIntegrationsettings postgres.StringExpression
	GetColonMessagetemplates       postgres.StringExpression
	GetColonPhonenumbers           postgres.StringExpression
}{
	GetColonOrganizationmember:     postgres.NewEnumValue("Get:OrganizationMember"),
	CreateColonOrganizationmember:  postgres.NewEnumValue("Create:OrganizationMember"),
	UpdateColonOrganizationmember:  postgres.NewEnumValue("Update:OrganizationMember"),
	DeleteColonOrganizationmember:  postgres.NewEnumValue("Delete:OrganizationMember"),
	GetColonCampaign:               postgres.NewEnumValue("Get:Campaign"),
	CreateColonCampaign:            postgres.NewEnumValue("Create:Campaign"),
	UpdateColonCampaign:            postgres.NewEnumValue("Update:Campaign"),
	DeleteColonCampaign:            postgres.NewEnumValue("Delete:Campaign"),
	GetColonConversation:           postgres.NewEnumValue("Get:Conversation"),
	UpdateColonConversation:        postgres.NewEnumValue("Update:Conversation"),
	DeleteColonConversation:        postgres.NewEnumValue("Delete:Conversation"),
	AssignColonConversation:        postgres.NewEnumValue("Assign:Conversation"),
	UnassignColonConversation:      postgres.NewEnumValue("Unassign:Conversation"),
	GetColonList:                   postgres.NewEnumValue("Get:List"),
	CreateColonList:                postgres.NewEnumValue("Create:List"),
	UpdateColonList:                postgres.NewEnumValue("Update:List"),
	DeleteColonList:                postgres.NewEnumValue("Delete:List"),
	GetColonTag:                    postgres.NewEnumValue("Get:Tag"),
	CreateColonTag:                 postgres.NewEnumValue("Create:Tag"),
	UpdateColonTag:                 postgres.NewEnumValue("Update:Tag"),
	DeleteColonTag:                 postgres.NewEnumValue("Delete:Tag"),
	GetColonApikey:                 postgres.NewEnumValue("Get:ApiKey"),
	RegenerateColonApikey:          postgres.NewEnumValue("Regenerate:ApiKey"),
	GetColonAppsettings:            postgres.NewEnumValue("Get:AppSettings"),
	UpdateColonAppsettings:         postgres.NewEnumValue("Update:AppSettings"),
	GetColonContact:                postgres.NewEnumValue("Get:Contact"),
	CreateColonContact:             postgres.NewEnumValue("Create:Contact"),
	UpdateColonContact:             postgres.NewEnumValue("Update:Contact"),
	DeleteColonContact:             postgres.NewEnumValue("Delete:Contact"),
	BulkimportColonContacts:        postgres.NewEnumValue("BulkImport:Contacts"),
	GetColonPrimaryanalytics:       postgres.NewEnumValue("Get:PrimaryAnalytics"),
	GetColonSecondaryanalytics:     postgres.NewEnumValue("Get:SecondaryAnalytics"),
	GetColonCampaignanalytics:      postgres.NewEnumValue("Get:CampaignAnalytics"),
	UpdateColonOrganization:        postgres.NewEnumValue("Update:Organization"),
	GetColonOrganizationrole:       postgres.NewEnumValue("Get:OrganizationRole"),
	CreateColonOrganizationrole:    postgres.NewEnumValue("Create:OrganizationRole"),
	UpdateColonOrganizationrole:    postgres.NewEnumValue("Update:OrganizationRole"),
	DeleteColonOrganizationrole:    postgres.NewEnumValue("Delete:OrganizationRole"),
	UpdateColonIntegrationsettings: postgres.NewEnumValue("Update:IntegrationSettings"),
	GetColonMessagetemplates:       postgres.NewEnumValue("Get:MessageTemplates"),
	GetColonPhonenumbers:           postgres.NewEnumValue("Get:PhoneNumbers"),
}
