//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var UserPermissionLevel = &struct {
	Owner  postgres.StringExpression
	Admin  postgres.StringExpression
	Member postgres.StringExpression
}{
	Owner:  postgres.NewEnumValue("Owner"),
	Admin:  postgres.NewEnumValue("Admin"),
	Member: postgres.NewEnumValue("Member"),
}
