// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package handlers

// ContactSchema defines model for ContactSchema.
type ContactSchema struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	CreatedAt  *string                 `json:"created_at,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Phone      *string                 `json:"phone,omitempty"`
	UniqueId   *int                    `json:"uniqueId,omitempty"`
	UpdatedAt  *string                 `json:"updated_at,omitempty"`
}

// LoginRequestBodySchema defines model for LoginRequestBodySchema.
type LoginRequestBodySchema struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// NewContactSchema defines model for NewContactSchema.
type NewContactSchema struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Phone      *string                 `json:"phone,omitempty"`
}

// UpdateContactSchema defines model for UpdateContactSchema.
type UpdateContactSchema struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Phone      *string                 `json:"phone,omitempty"`
}

// DeleteSubscriberByListParams defines parameters for DeleteSubscriberByList.
type DeleteSubscriberByListParams struct {
	// Id subscriber id/s to be deleted
	Id string `form:"id" json:"id"`
}

// GetSubscribersParams defines parameters for GetSubscribers.
type GetSubscribersParams struct {
	// Page number of records to skip
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// PerPage max number of records to return per page
	PerPage *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Query query subscribers with an SQL expression.
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody = NewContactSchema

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequestBodySchema

// UpdateContactByIdJSONRequestBody defines body for UpdateContactById for application/json ContentType.
type UpdateContactByIdJSONRequestBody = UpdateContactSchema
