// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package handlers

// Contact defines model for Contact.
type Contact struct {
	Data *struct {
		Attributes *map[string]interface{} `json:"attributes,omitempty"`
		CreatedAt  *string                 `json:"created_at,omitempty"`
		Name       *string                 `json:"name,omitempty"`
		Phone      *string                 `json:"phone,omitempty"`
		UniqueId   *int                    `json:"uniqueId,omitempty"`
		UpdatedAt  *string                 `json:"updated_at,omitempty"`
	} `json:"data,omitempty"`
}

// NewContact defines model for NewContact.
type NewContact struct {
	Data *struct {
		Attributes *map[string]interface{} `json:"attributes,omitempty"`
		Name       *string                 `json:"name,omitempty"`
		Phone      *string                 `json:"phone,omitempty"`
	} `json:"data,omitempty"`
}

// UpdateContact defines model for UpdateContact.
type UpdateContact struct {
	Data *struct {
		Attributes *map[string]interface{} `json:"attributes,omitempty"`
		Name       *string                 `json:"name,omitempty"`
		Phone      *string                 `json:"phone,omitempty"`
	} `json:"data,omitempty"`
}

// DeleteSubscriberByListParams defines parameters for DeleteSubscriberByList.
type DeleteSubscriberByListParams struct {
	// Id subscriber id/s to be deleted
	Id string `form:"id" json:"id"`
}

// GetSubscribersParams defines parameters for GetSubscribers.
type GetSubscribersParams struct {
	// Page number of records to skip
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// PerPage max number of records to return per page
	PerPage *int32 `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Query query subscribers with an SQL expression.
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody = NewContact

// UpdateContactByIdJSONRequestBody defines body for UpdateContactById for application/json ContentType.
type UpdateContactByIdJSONRequestBody = UpdateContact
