//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AccessLogSourceType string

const (
	AccessLogSourceType_WebInterface AccessLogSourceType = "WebInterface"
	AccessLogSourceType_ApiAccess    AccessLogSourceType = "ApiAccess"
)

func (e *AccessLogSourceType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "WebInterface":
		*e = AccessLogSourceType_WebInterface
	case "ApiAccess":
		*e = AccessLogSourceType_ApiAccess
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AccessLogSourceType enum")
	}

	return nil
}

func (e AccessLogSourceType) String() string {
	return string(e)
}
