//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AiApiCallLogs struct {
	UniqueId        uuid.UUID `sql:"primary_key"`
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Request         string
	Response        string
	InputTokenUsed  int32
	OutputTokenUsed int32
	OrganizationId  uuid.UUID
	Model           AiModelEnum
}
