//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AiChatMessageRoleEnum string

const (
	AiChatMessageRoleEnum_System    AiChatMessageRoleEnum = "System"
	AiChatMessageRoleEnum_User      AiChatMessageRoleEnum = "User"
	AiChatMessageRoleEnum_Assistant AiChatMessageRoleEnum = "Assistant"
	AiChatMessageRoleEnum_Data      AiChatMessageRoleEnum = "Data"
)

func (e *AiChatMessageRoleEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "System":
		*e = AiChatMessageRoleEnum_System
	case "User":
		*e = AiChatMessageRoleEnum_User
	case "Assistant":
		*e = AiChatMessageRoleEnum_Assistant
	case "Data":
		*e = AiChatMessageRoleEnum_Data
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AiChatMessageRoleEnum enum")
	}

	return nil
}

func (e AiChatMessageRoleEnum) String() string {
	return string(e)
}
