//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AiChatStatusEnum string

const (
	AiChatStatusEnum_Active   AiChatStatusEnum = "Active"
	AiChatStatusEnum_Inactive AiChatStatusEnum = "Inactive"
)

func (e *AiChatStatusEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Active":
		*e = AiChatStatusEnum_Active
	case "Inactive":
		*e = AiChatStatusEnum_Inactive
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AiChatStatusEnum enum")
	}

	return nil
}

func (e AiChatStatusEnum) String() string {
	return string(e)
}
