//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Campaign struct {
	UniqueId                           uuid.UUID `sql:"primary_key"`
	CreatedAt                          time.Time
	UpdatedAt                          time.Time
	Description                        *string
	Name                               string
	Status                             CampaignStatusEnum
	LastContactSent                    *uuid.UUID
	IsLinkTrackingEnabled              bool
	CreatedByOrganizationMemberId      uuid.UUID
	ScheduledAt 					  *time.Time
	OrganizationId                     uuid.UUID
	MessageTemplateId                  *string
	PhoneNumber                        string
	TemplateMessageComponentParameters *string
}
