//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CurrencyCodeEnum string

const (
	CurrencyCodeEnum_Usd CurrencyCodeEnum = "USD"
	CurrencyCodeEnum_Eur CurrencyCodeEnum = "EUR"
	CurrencyCodeEnum_Jpy CurrencyCodeEnum = "JPY"
	CurrencyCodeEnum_Gbp CurrencyCodeEnum = "GBP"
	CurrencyCodeEnum_Aud CurrencyCodeEnum = "AUD"
	CurrencyCodeEnum_Cad CurrencyCodeEnum = "CAD"
	CurrencyCodeEnum_Chf CurrencyCodeEnum = "CHF"
	CurrencyCodeEnum_Cny CurrencyCodeEnum = "CNY"
	CurrencyCodeEnum_Sek CurrencyCodeEnum = "SEK"
	CurrencyCodeEnum_Nzd CurrencyCodeEnum = "NZD"
	CurrencyCodeEnum_Inr CurrencyCodeEnum = "INR"
	CurrencyCodeEnum_Rub CurrencyCodeEnum = "RUB"
	CurrencyCodeEnum_Brl CurrencyCodeEnum = "BRL"
	CurrencyCodeEnum_Zar CurrencyCodeEnum = "ZAR"
	CurrencyCodeEnum_Mxn CurrencyCodeEnum = "MXN"
	CurrencyCodeEnum_Sgd CurrencyCodeEnum = "SGD"
	CurrencyCodeEnum_Hkd CurrencyCodeEnum = "HKD"
	CurrencyCodeEnum_Nok CurrencyCodeEnum = "NOK"
	CurrencyCodeEnum_Krw CurrencyCodeEnum = "KRW"
	CurrencyCodeEnum_Try CurrencyCodeEnum = "TRY"
	CurrencyCodeEnum_Idr CurrencyCodeEnum = "IDR"
	CurrencyCodeEnum_Thb CurrencyCodeEnum = "THB"
	CurrencyCodeEnum_Myr CurrencyCodeEnum = "MYR"
	CurrencyCodeEnum_Php CurrencyCodeEnum = "PHP"
	CurrencyCodeEnum_Pln CurrencyCodeEnum = "PLN"
	CurrencyCodeEnum_Dkk CurrencyCodeEnum = "DKK"
	CurrencyCodeEnum_Huf CurrencyCodeEnum = "HUF"
	CurrencyCodeEnum_Czk CurrencyCodeEnum = "CZK"
	CurrencyCodeEnum_Ils CurrencyCodeEnum = "ILS"
	CurrencyCodeEnum_Clp CurrencyCodeEnum = "CLP"
	CurrencyCodeEnum_Pkr CurrencyCodeEnum = "PKR"
	CurrencyCodeEnum_Aed CurrencyCodeEnum = "AED"
	CurrencyCodeEnum_Cop CurrencyCodeEnum = "COP"
	CurrencyCodeEnum_Sar CurrencyCodeEnum = "SAR"
	CurrencyCodeEnum_Twd CurrencyCodeEnum = "TWD"
	CurrencyCodeEnum_Vnd CurrencyCodeEnum = "VND"
	CurrencyCodeEnum_Ngn CurrencyCodeEnum = "NGN"
	CurrencyCodeEnum_Bdt CurrencyCodeEnum = "BDT"
	CurrencyCodeEnum_Egp CurrencyCodeEnum = "EGP"
	CurrencyCodeEnum_Kzt CurrencyCodeEnum = "KZT"
	CurrencyCodeEnum_Qar CurrencyCodeEnum = "QAR"
	CurrencyCodeEnum_Kes CurrencyCodeEnum = "KES"
	CurrencyCodeEnum_Lkr CurrencyCodeEnum = "LKR"
	CurrencyCodeEnum_Pen CurrencyCodeEnum = "PEN"
	CurrencyCodeEnum_Uah CurrencyCodeEnum = "UAH"
	CurrencyCodeEnum_Ron CurrencyCodeEnum = "RON"
	CurrencyCodeEnum_Zmw CurrencyCodeEnum = "ZMW"
	CurrencyCodeEnum_Omr CurrencyCodeEnum = "OMR"
)

func (e *CurrencyCodeEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "USD":
		*e = CurrencyCodeEnum_Usd
	case "EUR":
		*e = CurrencyCodeEnum_Eur
	case "JPY":
		*e = CurrencyCodeEnum_Jpy
	case "GBP":
		*e = CurrencyCodeEnum_Gbp
	case "AUD":
		*e = CurrencyCodeEnum_Aud
	case "CAD":
		*e = CurrencyCodeEnum_Cad
	case "CHF":
		*e = CurrencyCodeEnum_Chf
	case "CNY":
		*e = CurrencyCodeEnum_Cny
	case "SEK":
		*e = CurrencyCodeEnum_Sek
	case "NZD":
		*e = CurrencyCodeEnum_Nzd
	case "INR":
		*e = CurrencyCodeEnum_Inr
	case "RUB":
		*e = CurrencyCodeEnum_Rub
	case "BRL":
		*e = CurrencyCodeEnum_Brl
	case "ZAR":
		*e = CurrencyCodeEnum_Zar
	case "MXN":
		*e = CurrencyCodeEnum_Mxn
	case "SGD":
		*e = CurrencyCodeEnum_Sgd
	case "HKD":
		*e = CurrencyCodeEnum_Hkd
	case "NOK":
		*e = CurrencyCodeEnum_Nok
	case "KRW":
		*e = CurrencyCodeEnum_Krw
	case "TRY":
		*e = CurrencyCodeEnum_Try
	case "IDR":
		*e = CurrencyCodeEnum_Idr
	case "THB":
		*e = CurrencyCodeEnum_Thb
	case "MYR":
		*e = CurrencyCodeEnum_Myr
	case "PHP":
		*e = CurrencyCodeEnum_Php
	case "PLN":
		*e = CurrencyCodeEnum_Pln
	case "DKK":
		*e = CurrencyCodeEnum_Dkk
	case "HUF":
		*e = CurrencyCodeEnum_Huf
	case "CZK":
		*e = CurrencyCodeEnum_Czk
	case "ILS":
		*e = CurrencyCodeEnum_Ils
	case "CLP":
		*e = CurrencyCodeEnum_Clp
	case "PKR":
		*e = CurrencyCodeEnum_Pkr
	case "AED":
		*e = CurrencyCodeEnum_Aed
	case "COP":
		*e = CurrencyCodeEnum_Cop
	case "SAR":
		*e = CurrencyCodeEnum_Sar
	case "TWD":
		*e = CurrencyCodeEnum_Twd
	case "VND":
		*e = CurrencyCodeEnum_Vnd
	case "NGN":
		*e = CurrencyCodeEnum_Ngn
	case "BDT":
		*e = CurrencyCodeEnum_Bdt
	case "EGP":
		*e = CurrencyCodeEnum_Egp
	case "KZT":
		*e = CurrencyCodeEnum_Kzt
	case "QAR":
		*e = CurrencyCodeEnum_Qar
	case "KES":
		*e = CurrencyCodeEnum_Kes
	case "LKR":
		*e = CurrencyCodeEnum_Lkr
	case "PEN":
		*e = CurrencyCodeEnum_Pen
	case "UAH":
		*e = CurrencyCodeEnum_Uah
	case "RON":
		*e = CurrencyCodeEnum_Ron
	case "ZMW":
		*e = CurrencyCodeEnum_Zmw
	case "OMR":
		*e = CurrencyCodeEnum_Omr
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CurrencyCodeEnum enum")
	}

	return nil
}

func (e CurrencyCodeEnum) String() string {
	return string(e)
}
