//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type MessageReply struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MessageId      uuid.UUID `sql:"primary_key"`
	ReplyMessageId uuid.UUID `sql:"primary_key"`
}
