//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OrganizaRolePermissionEnum string

const (
	OrganizaRolePermissionEnum_GetTeam                    OrganizaRolePermissionEnum = "GetTeam"
	OrganizaRolePermissionEnum_UpdateTeam                 OrganizaRolePermissionEnum = "UpdateTeam"
	OrganizaRolePermissionEnum_GetCampaign                OrganizaRolePermissionEnum = "GetCampaign"
	OrganizaRolePermissionEnum_CreateCampaign             OrganizaRolePermissionEnum = "CreateCampaign"
	OrganizaRolePermissionEnum_UpdateCampaign             OrganizaRolePermissionEnum = "UpdateCampaign"
	OrganizaRolePermissionEnum_DeleteCampaign             OrganizaRolePermissionEnum = "DeleteCampaign"
	OrganizaRolePermissionEnum_GetConversations           OrganizaRolePermissionEnum = "GetConversations"
	OrganizaRolePermissionEnum_GetConversation            OrganizaRolePermissionEnum = "GetConversation"
	OrganizaRolePermissionEnum_UpdateConversation         OrganizaRolePermissionEnum = "UpdateConversation"
	OrganizaRolePermissionEnum_DeleteConversation         OrganizaRolePermissionEnum = "DeleteConversation"
	OrganizaRolePermissionEnum_AssignConversation         OrganizaRolePermissionEnum = "AssignConversation"
	OrganizaRolePermissionEnum_UnassignConversation       OrganizaRolePermissionEnum = "UnassignConversation"
	OrganizaRolePermissionEnum_GetMessages                OrganizaRolePermissionEnum = "GetMessages"
	OrganizaRolePermissionEnum_GetList                    OrganizaRolePermissionEnum = "GetList"
	OrganizaRolePermissionEnum_CreateList                 OrganizaRolePermissionEnum = "CreateList"
	OrganizaRolePermissionEnum_UpdateList                 OrganizaRolePermissionEnum = "UpdateList"
	OrganizaRolePermissionEnum_DeleteList                 OrganizaRolePermissionEnum = "DeleteList"
	OrganizaRolePermissionEnum_GetApiKey                  OrganizaRolePermissionEnum = "GetApiKey"
	OrganizaRolePermissionEnum_RegenerateApiKey           OrganizaRolePermissionEnum = "RegenerateApiKey"
	OrganizaRolePermissionEnum_GetAppSettings             OrganizaRolePermissionEnum = "GetAppSettings"
	OrganizaRolePermissionEnum_UpdateAppSettings          OrganizaRolePermissionEnum = "UpdateAppSettings"
	OrganizaRolePermissionEnum_GetContacts                OrganizaRolePermissionEnum = "GetContacts"
	OrganizaRolePermissionEnum_GetContact                 OrganizaRolePermissionEnum = "GetContact"
	OrganizaRolePermissionEnum_CreateContact              OrganizaRolePermissionEnum = "CreateContact"
	OrganizaRolePermissionEnum_UpdateContact              OrganizaRolePermissionEnum = "UpdateContact"
	OrganizaRolePermissionEnum_DeleteContact              OrganizaRolePermissionEnum = "DeleteContact"
	OrganizaRolePermissionEnum_BulkImportContacts         OrganizaRolePermissionEnum = "BulkImportContacts"
	OrganizaRolePermissionEnum_GetPrimaryAnalytics        OrganizaRolePermissionEnum = "GetPrimaryAnalytics"
	OrganizaRolePermissionEnum_GetSecondaryAnalytics      OrganizaRolePermissionEnum = "GetSecondaryAnalytics"
	OrganizaRolePermissionEnum_GetCampaignAnalytics       OrganizaRolePermissionEnum = "GetCampaignAnalytics"
	OrganizaRolePermissionEnum_GetCampaignsAnalytics      OrganizaRolePermissionEnum = "GetCampaignsAnalytics"
	OrganizaRolePermissionEnum_GetMetadata                OrganizaRolePermissionEnum = "GetMetadata"
	OrganizaRolePermissionEnum_GetOrganizations           OrganizaRolePermissionEnum = "GetOrganizations"
	OrganizaRolePermissionEnum_CreateOrganization         OrganizaRolePermissionEnum = "CreateOrganization"
	OrganizaRolePermissionEnum_GetOrganization            OrganizaRolePermissionEnum = "GetOrganization"
	OrganizaRolePermissionEnum_UpdateOrganization         OrganizaRolePermissionEnum = "UpdateOrganization"
	OrganizaRolePermissionEnum_TransferOwnership          OrganizaRolePermissionEnum = "TransferOwnership"
	OrganizaRolePermissionEnum_ManageOrganizationSettings OrganizaRolePermissionEnum = "ManageOrganizationSettings"
	OrganizaRolePermissionEnum_ManageOrganizationTags     OrganizaRolePermissionEnum = "ManageOrganizationTags"
	OrganizaRolePermissionEnum_ManageOrganizationInvites  OrganizaRolePermissionEnum = "ManageOrganizationInvites"
	OrganizaRolePermissionEnum_GetMembers                 OrganizaRolePermissionEnum = "GetMembers"
	OrganizaRolePermissionEnum_ManageMember               OrganizaRolePermissionEnum = "ManageMember"
	OrganizaRolePermissionEnum_AssignRoleToMember         OrganizaRolePermissionEnum = "AssignRoleToMember"
	OrganizaRolePermissionEnum_ManageRoles                OrganizaRolePermissionEnum = "ManageRoles"
	OrganizaRolePermissionEnum_ManageRole                 OrganizaRolePermissionEnum = "ManageRole"
	OrganizaRolePermissionEnum_ManageIntegrations         OrganizaRolePermissionEnum = "ManageIntegrations"
	OrganizaRolePermissionEnum_SwitchOrganization         OrganizaRolePermissionEnum = "SwitchOrganization"
	OrganizaRolePermissionEnum_JoinOrganization           OrganizaRolePermissionEnum = "JoinOrganization"
)

func (e *OrganizaRolePermissionEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "GetTeam":
		*e = OrganizaRolePermissionEnum_GetTeam
	case "UpdateTeam":
		*e = OrganizaRolePermissionEnum_UpdateTeam
	case "GetCampaign":
		*e = OrganizaRolePermissionEnum_GetCampaign
	case "CreateCampaign":
		*e = OrganizaRolePermissionEnum_CreateCampaign
	case "UpdateCampaign":
		*e = OrganizaRolePermissionEnum_UpdateCampaign
	case "DeleteCampaign":
		*e = OrganizaRolePermissionEnum_DeleteCampaign
	case "GetConversations":
		*e = OrganizaRolePermissionEnum_GetConversations
	case "GetConversation":
		*e = OrganizaRolePermissionEnum_GetConversation
	case "UpdateConversation":
		*e = OrganizaRolePermissionEnum_UpdateConversation
	case "DeleteConversation":
		*e = OrganizaRolePermissionEnum_DeleteConversation
	case "AssignConversation":
		*e = OrganizaRolePermissionEnum_AssignConversation
	case "UnassignConversation":
		*e = OrganizaRolePermissionEnum_UnassignConversation
	case "GetMessages":
		*e = OrganizaRolePermissionEnum_GetMessages
	case "GetList":
		*e = OrganizaRolePermissionEnum_GetList
	case "CreateList":
		*e = OrganizaRolePermissionEnum_CreateList
	case "UpdateList":
		*e = OrganizaRolePermissionEnum_UpdateList
	case "DeleteList":
		*e = OrganizaRolePermissionEnum_DeleteList
	case "GetApiKey":
		*e = OrganizaRolePermissionEnum_GetApiKey
	case "RegenerateApiKey":
		*e = OrganizaRolePermissionEnum_RegenerateApiKey
	case "GetAppSettings":
		*e = OrganizaRolePermissionEnum_GetAppSettings
	case "UpdateAppSettings":
		*e = OrganizaRolePermissionEnum_UpdateAppSettings
	case "GetContacts":
		*e = OrganizaRolePermissionEnum_GetContacts
	case "GetContact":
		*e = OrganizaRolePermissionEnum_GetContact
	case "CreateContact":
		*e = OrganizaRolePermissionEnum_CreateContact
	case "UpdateContact":
		*e = OrganizaRolePermissionEnum_UpdateContact
	case "DeleteContact":
		*e = OrganizaRolePermissionEnum_DeleteContact
	case "BulkImportContacts":
		*e = OrganizaRolePermissionEnum_BulkImportContacts
	case "GetPrimaryAnalytics":
		*e = OrganizaRolePermissionEnum_GetPrimaryAnalytics
	case "GetSecondaryAnalytics":
		*e = OrganizaRolePermissionEnum_GetSecondaryAnalytics
	case "GetCampaignAnalytics":
		*e = OrganizaRolePermissionEnum_GetCampaignAnalytics
	case "GetCampaignsAnalytics":
		*e = OrganizaRolePermissionEnum_GetCampaignsAnalytics
	case "GetMetadata":
		*e = OrganizaRolePermissionEnum_GetMetadata
	case "GetOrganizations":
		*e = OrganizaRolePermissionEnum_GetOrganizations
	case "CreateOrganization":
		*e = OrganizaRolePermissionEnum_CreateOrganization
	case "GetOrganization":
		*e = OrganizaRolePermissionEnum_GetOrganization
	case "UpdateOrganization":
		*e = OrganizaRolePermissionEnum_UpdateOrganization
	case "TransferOwnership":
		*e = OrganizaRolePermissionEnum_TransferOwnership
	case "ManageOrganizationSettings":
		*e = OrganizaRolePermissionEnum_ManageOrganizationSettings
	case "ManageOrganizationTags":
		*e = OrganizaRolePermissionEnum_ManageOrganizationTags
	case "ManageOrganizationInvites":
		*e = OrganizaRolePermissionEnum_ManageOrganizationInvites
	case "GetMembers":
		*e = OrganizaRolePermissionEnum_GetMembers
	case "ManageMember":
		*e = OrganizaRolePermissionEnum_ManageMember
	case "AssignRoleToMember":
		*e = OrganizaRolePermissionEnum_AssignRoleToMember
	case "ManageRoles":
		*e = OrganizaRolePermissionEnum_ManageRoles
	case "ManageRole":
		*e = OrganizaRolePermissionEnum_ManageRole
	case "ManageIntegrations":
		*e = OrganizaRolePermissionEnum_ManageIntegrations
	case "SwitchOrganization":
		*e = OrganizaRolePermissionEnum_SwitchOrganization
	case "JoinOrganization":
		*e = OrganizaRolePermissionEnum_JoinOrganization
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OrganizaRolePermissionEnum enum")
	}

	return nil
}

func (e OrganizaRolePermissionEnum) String() string {
	return string(e)
}
