//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PricingPlanStatusEnum string

const (
	PricingPlanStatusEnum_Active   PricingPlanStatusEnum = "Active"
	PricingPlanStatusEnum_Inactive PricingPlanStatusEnum = "Inactive"
)

func (e *PricingPlanStatusEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Active":
		*e = PricingPlanStatusEnum_Active
	case "Inactive":
		*e = PricingPlanStatusEnum_Inactive
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PricingPlanStatusEnum enum")
	}

	return nil
}

func (e PricingPlanStatusEnum) String() string {
	return string(e)
}
