//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserPermissionLevelEnum string

const (
	UserPermissionLevelEnum_Owner  UserPermissionLevelEnum = "Owner"
	UserPermissionLevelEnum_Member UserPermissionLevelEnum = "Member"
)

func (e *UserPermissionLevelEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Owner":
		*e = UserPermissionLevelEnum_Owner
	case "Member":
		*e = UserPermissionLevelEnum_Member
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserPermissionLevelEnum enum")
	}

	return nil
}

func (e UserPermissionLevelEnum) String() string {
	return string(e)
}
