//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserAccountStatusEnum string

const (
	UserAccountStatusEnum_Active    UserAccountStatusEnum = "active"
	UserAccountStatusEnum_Deleted   UserAccountStatusEnum = "deleted"
	UserAccountStatusEnum_Suspended UserAccountStatusEnum = "suspended"
)

func (e *UserAccountStatusEnum) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "active":
		*e = UserAccountStatusEnum_Active
	case "deleted":
		*e = UserAccountStatusEnum_Deleted
	case "suspended":
		*e = UserAccountStatusEnum_Suspended
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserAccountStatusEnum enum")
	}

	return nil
}

func (e UserAccountStatusEnum) String() string {
	return string(e)
}
