//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type WhatsAppBusinessAccountVerificationStatus string

const (
	WhatsAppBusinessAccountVerificationStatus_Verified   WhatsAppBusinessAccountVerificationStatus = "Verified"
	WhatsAppBusinessAccountVerificationStatus_Unverified WhatsAppBusinessAccountVerificationStatus = "Unverified"
)

func (e *WhatsAppBusinessAccountVerificationStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Verified":
		*e = WhatsAppBusinessAccountVerificationStatus_Verified
	case "Unverified":
		*e = WhatsAppBusinessAccountVerificationStatus_Unverified
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for WhatsAppBusinessAccountVerificationStatus enum")
	}

	return nil
}

func (e WhatsAppBusinessAccountVerificationStatus) String() string {
	return string(e)
}
