//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DiscountCoupon = newDiscountCouponTable("public", "DiscountCoupon", "")

type discountCouponTable struct {
	postgres.Table

	// Columns
	UniqueId           postgres.ColumnString
	CreatedAt          postgres.ColumnTimestamp
	UpdatedAt          postgres.ColumnTimestamp
	DiscountPercentage postgres.ColumnFloat
	DiscountCode       postgres.ColumnString
	ExpiredAt          postgres.ColumnTimestamp
	MaxUsageAllowed    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type DiscountCouponTable struct {
	discountCouponTable

	EXCLUDED discountCouponTable
}

// AS creates new DiscountCouponTable with assigned alias
func (a DiscountCouponTable) AS(alias string) *DiscountCouponTable {
	return newDiscountCouponTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DiscountCouponTable with assigned schema name
func (a DiscountCouponTable) FromSchema(schemaName string) *DiscountCouponTable {
	return newDiscountCouponTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DiscountCouponTable with assigned table prefix
func (a DiscountCouponTable) WithPrefix(prefix string) *DiscountCouponTable {
	return newDiscountCouponTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DiscountCouponTable with assigned table suffix
func (a DiscountCouponTable) WithSuffix(suffix string) *DiscountCouponTable {
	return newDiscountCouponTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDiscountCouponTable(schemaName, tableName, alias string) *DiscountCouponTable {
	return &DiscountCouponTable{
		discountCouponTable: newDiscountCouponTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newDiscountCouponTableImpl("", "excluded", ""),
	}
}

func newDiscountCouponTableImpl(schemaName, tableName, alias string) discountCouponTable {
	var (
		UniqueIdColumn           = postgres.StringColumn("UniqueId")
		CreatedAtColumn          = postgres.TimestampColumn("CreatedAt")
		UpdatedAtColumn          = postgres.TimestampColumn("UpdatedAt")
		DiscountPercentageColumn = postgres.FloatColumn("DiscountPercentage")
		DiscountCodeColumn       = postgres.StringColumn("DiscountCode")
		ExpiredAtColumn          = postgres.TimestampColumn("ExpiredAt")
		MaxUsageAllowedColumn    = postgres.IntegerColumn("MaxUsageAllowed")
		allColumns               = postgres.ColumnList{UniqueIdColumn, CreatedAtColumn, UpdatedAtColumn, DiscountPercentageColumn, DiscountCodeColumn, ExpiredAtColumn, MaxUsageAllowedColumn}
		mutableColumns           = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DiscountPercentageColumn, DiscountCodeColumn, ExpiredAtColumn, MaxUsageAllowedColumn}
	)

	return discountCouponTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UniqueId:           UniqueIdColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,
		DiscountPercentage: DiscountPercentageColumn,
		DiscountCode:       DiscountCodeColumn,
		ExpiredAt:          ExpiredAtColumn,
		MaxUsageAllowed:    MaxUsageAllowedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
