//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var WhatsappBusinessAccountPhoneNumber = newWhatsappBusinessAccountPhoneNumberTable("public", "WhatsappBusinessAccountPhoneNumber", "")

type whatsappBusinessAccountPhoneNumberTable struct {
	postgres.Table

	// Columns
	UniqueId                  postgres.ColumnString
	CreatedAt                 postgres.ColumnTimestampz
	UpdatedAt                 postgres.ColumnTimestampz
	WhatsappBusinessAccountId postgres.ColumnString
	MetaTitle                 postgres.ColumnString
	MetaDescription           postgres.ColumnString
	PhoneNumber               postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type WhatsappBusinessAccountPhoneNumberTable struct {
	whatsappBusinessAccountPhoneNumberTable

	EXCLUDED whatsappBusinessAccountPhoneNumberTable
}

// AS creates new WhatsappBusinessAccountPhoneNumberTable with assigned alias
func (a WhatsappBusinessAccountPhoneNumberTable) AS(alias string) *WhatsappBusinessAccountPhoneNumberTable {
	return newWhatsappBusinessAccountPhoneNumberTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WhatsappBusinessAccountPhoneNumberTable with assigned schema name
func (a WhatsappBusinessAccountPhoneNumberTable) FromSchema(schemaName string) *WhatsappBusinessAccountPhoneNumberTable {
	return newWhatsappBusinessAccountPhoneNumberTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WhatsappBusinessAccountPhoneNumberTable with assigned table prefix
func (a WhatsappBusinessAccountPhoneNumberTable) WithPrefix(prefix string) *WhatsappBusinessAccountPhoneNumberTable {
	return newWhatsappBusinessAccountPhoneNumberTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WhatsappBusinessAccountPhoneNumberTable with assigned table suffix
func (a WhatsappBusinessAccountPhoneNumberTable) WithSuffix(suffix string) *WhatsappBusinessAccountPhoneNumberTable {
	return newWhatsappBusinessAccountPhoneNumberTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWhatsappBusinessAccountPhoneNumberTable(schemaName, tableName, alias string) *WhatsappBusinessAccountPhoneNumberTable {
	return &WhatsappBusinessAccountPhoneNumberTable{
		whatsappBusinessAccountPhoneNumberTable: newWhatsappBusinessAccountPhoneNumberTableImpl(schemaName, tableName, alias),
		EXCLUDED:                                newWhatsappBusinessAccountPhoneNumberTableImpl("", "excluded", ""),
	}
}

func newWhatsappBusinessAccountPhoneNumberTableImpl(schemaName, tableName, alias string) whatsappBusinessAccountPhoneNumberTable {
	var (
		UniqueIdColumn                  = postgres.StringColumn("UniqueId")
		CreatedAtColumn                 = postgres.TimestampzColumn("CreatedAt")
		UpdatedAtColumn                 = postgres.TimestampzColumn("UpdatedAt")
		WhatsappBusinessAccountIdColumn = postgres.StringColumn("WhatsappBusinessAccountId")
		MetaTitleColumn                 = postgres.StringColumn("MetaTitle")
		MetaDescriptionColumn           = postgres.StringColumn("MetaDescription")
		PhoneNumberColumn               = postgres.StringColumn("PhoneNumber")
		allColumns                      = postgres.ColumnList{UniqueIdColumn, CreatedAtColumn, UpdatedAtColumn, WhatsappBusinessAccountIdColumn, MetaTitleColumn, MetaDescriptionColumn, PhoneNumberColumn}
		mutableColumns                  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, WhatsappBusinessAccountIdColumn, MetaTitleColumn, MetaDescriptionColumn, PhoneNumberColumn}
	)

	return whatsappBusinessAccountPhoneNumberTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UniqueId:                  UniqueIdColumn,
		CreatedAt:                 CreatedAtColumn,
		UpdatedAt:                 UpdatedAtColumn,
		WhatsappBusinessAccountId: WhatsappBusinessAccountIdColumn,
		MetaTitle:                 MetaTitleColumn,
		MetaDescription:           MetaDescriptionColumn,
		PhoneNumber:               PhoneNumberColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
